using Kaisa.Digivice.Extensions;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using sysrand = System.Random;

namespace Kaisa.Digivice.App {
    /* Enemies have three different sets of attacks, generated at random for every game. Each battle, they will use one of these three set of attacks.
     * To achieve this, the saved game has 3 seeds stored and, when a battle commences, one of these 3 seeds is used to create a new sysrand object (battleRNG).
     * Only the enemy attack every turn uses this battleRNG object – other random effects use UnityEngine.Random as to not interfere with the numbers
     * being randomly generated by this object for the enemy attacks.
     */
    public class Battle : DigiviceApp {
        private enum BattleScreen {
            MainScreen,
            BattleCall_DDocks,
            BattleCall_Menu,
            AttackMenu
        }

        #region Input
        public override void InputA() {
            if (currentScreen == BattleScreen.MainScreen) {
                if(menuIndex == 0) {
                    audioMgr.PlayButtonA();
                    OpenDDocks();
                }
            }
            else if (currentScreen == BattleScreen.BattleCall_DDocks) {
                if(isDDockUsed[ddockIndex]) {
                    audioMgr.PlayButtonB();
                }
                else {
                    audioMgr.PlayButtonA();
                    ChooseCurrentDDock();
                }
            }
            else if (currentScreen == BattleScreen.BattleCall_Menu) {
                if(battleCallMenuIndex == 0) {
                    audioMgr.PlayButtonA();
                    currentScreen = BattleScreen.AttackMenu;
                    attackIndex = 0;
                }
                else if (battleCallMenuIndex == 3) {
                    audioMgr.PlayButtonA();
                    DeportCurrentDigimon();
                }
            }
            else if (currentScreen == BattleScreen.AttackMenu) {
                audioMgr.PlayButtonA();
                SubmitTurn(attackIndex);
            }
        }
        public override void InputB() {
            if (currentScreen == BattleScreen.MainScreen) {
                audioMgr.PlayButtonB();
            }
            else if (currentScreen == BattleScreen.BattleCall_DDocks) {
                CloseDDocks();
                audioMgr.PlayButtonB();
            }
            else if (currentScreen == BattleScreen.BattleCall_Menu) {
                audioMgr.PlayButtonB();
            }
            else if (currentScreen == BattleScreen.AttackMenu) {
                audioMgr.PlayButtonB();
                currentScreen = BattleScreen.BattleCall_Menu;
            }
        }
        public override void InputLeft() {
            if(currentScreen == BattleScreen.MainScreen) {
                audioMgr.PlayButtonA();
                menuIndex = menuIndex.CircularAdd(-1, 3);
            }
            else if (currentScreen == BattleScreen.BattleCall_DDocks) {
                audioMgr.PlayButtonA();
                ddockIndex = ddockIndex.CircularAdd(-1, 3);
            }
            else if (currentScreen == BattleScreen.BattleCall_Menu) {
                audioMgr.PlayButtonA();
                battleCallMenuIndex = battleCallMenuIndex.CircularAdd(-1, 3);
            }
            else if (currentScreen == BattleScreen.AttackMenu) {
                audioMgr.PlayButtonA();
                attackIndex = attackIndex.CircularAdd(-1, 2);
            }
        }
        public override void InputRight() {
            if (currentScreen == BattleScreen.MainScreen) {
                audioMgr.PlayButtonA();
                menuIndex = menuIndex.CircularAdd(1, 3);
            }
            else if (currentScreen == BattleScreen.BattleCall_DDocks) {
                audioMgr.PlayButtonA();
                ddockIndex = ddockIndex.CircularAdd(1, 3);
            }
            else if (currentScreen == BattleScreen.BattleCall_Menu) {
                audioMgr.PlayButtonA();
                battleCallMenuIndex = battleCallMenuIndex.CircularAdd(1, 3);
            }
            else if (currentScreen == BattleScreen.AttackMenu) {
                audioMgr.PlayButtonA();
                attackIndex = attackIndex.CircularAdd(1, 2);
            }
        }
        #endregion

        //Tools:
        private sysrand enemyAttackRNG;

        //Battle information:
        private int victoryExp, defeatExp; //The amounts of experience the player will win or lose depending on the outcome of the battle.
        private int playerLevel;

        private bool isBossBattle;
        private int bossLevel;
        private bool[] isDDockUsed = new bool[4] { false, false, false, false };
        private int _currentCallPoints = 10; //Do not use this variable.

        private int CurrentCallPoints {
            get => _currentCallPoints;
            set {
                if (value > 10) value = 10;
                if (value < 0) value = 0;
                _currentCallPoints = value;
            }
        }

        private Digimon friendlyDigimon;
        private MutableCombatStats friendlyStats;
        private bool awardSpiritPower = false; //Only digimons summoned from Battle Call award Spirit Power.

        private Digimon enemyDigimon;
        private MutableCombatStats enemyStats;

        //Menus and navigation
        private BattleScreen currentScreen = BattleScreen.MainScreen;
        private byte menuIndex = 0; //0: Battle call, 1: Spirit on, 2: Digits, 3: Escape.
        private byte ddockIndex = 0; //D-Docks 0 to 3.
        private byte battleCallMenuIndex = 0; //0: Attack, 1: Digivolve, 2: Battle Card, 3: Deport.
        private byte attackIndex = 0; //0: Energy, 1: Crush, 2: Ability.

        protected override void StartApp() {
            enemyDigimon = gm.DatabaseMgr.GetDigimon(appArgs[0]);
            //Check for errors:
            if (enemyDigimon == null) {
                VisualDebug.WriteLine($"The digimon passed to the Battle app ({appArgs[0]}) couldn't be found.");
            }

            playerLevel = gm.logicMgr.GetPlayerLevel();
            InitializeRNG();

            if (appArgs.Length == 2) {
                isBossBattle = (appArgs[1] == "true");
            }

            if(isBossBattle) {
                gm.EnqueueAnimation(gm.screenMgr.AEncounterBoss(enemyDigimon.name));

                bossLevel = gm.logicMgr.GetPlayerLevel();
                enemyStats = enemyDigimon.GetBossStats(bossLevel);
                VisualDebug.WriteLine($"Boss stats for level {bossLevel}: {enemyStats}");

                victoryExp = gm.logicMgr.ExperienceGained(playerLevel, bossLevel);
                defeatExp = gm.logicMgr.ExperienceGained(bossLevel, playerLevel);
            }
            else {
                gm.EnqueueAnimation(gm.screenMgr.AEncounterEnemy(enemyDigimon.name));

                enemyStats = enemyDigimon.GetRegularStats();
                VisualDebug.WriteLine($"Enemy stats: {enemyStats}");

                victoryExp = gm.logicMgr.ExperienceGained(playerLevel, enemyDigimon.baseLevel);
                defeatExp = gm.logicMgr.ExperienceGained(enemyDigimon.baseLevel, playerLevel);
            }

            gm.UpdateLeaverBuster(defeatExp, "");
            InvokeRepeating("DrawScreen", 0f, 0.05f);
        }

        private void Update() {
            //DrawScreen();
        }

        private void DrawScreen() {
            ClearScreen();

            if(currentScreen == BattleScreen.MainScreen) {
                SetScreen(gm.spriteDB.battle_mainMenu[menuIndex]);
            }
            else if (currentScreen == BattleScreen.BattleCall_DDocks) {
                gm.BuildDDockSprite(ddockIndex, Parent);
            }
            else if (currentScreen == BattleScreen.BattleCall_Menu) {
                if (battleCallMenuIndex == 0) SetScreen(gm.spriteDB.battle_combatMenu[0]); //Attack
                if (battleCallMenuIndex == 1) SetScreen(gm.spriteDB.battle_combatMenu[1]); //Digivolve
                if (battleCallMenuIndex == 2) SetScreen(gm.spriteDB.battle_combatMenu[2]); //Battle card
                if (battleCallMenuIndex == 3) SetScreen(gm.spriteDB.battle_combatMenu[4]); //Deport
            }
            else if (currentScreen == BattleScreen.AttackMenu) {
                SetScreen(gm.spriteDB.battle_attackMenu[attackIndex]);
            }
        }

        private void InitializeRNG() {
            int battleSeed = gm.GetRandomSavedSeed();
            enemyAttackRNG = new sysrand(battleSeed);
        }

        private void OpenDDocks() {
            currentScreen = BattleScreen.BattleCall_DDocks;
            ddockIndex = 0;
        }

        private void CloseDDocks() {
            currentScreen = BattleScreen.MainScreen;
        }

        private void ChooseCurrentDDock() {
            //If the player has no call points left, he will summon Numemon regardless of their choice.
            string digimon = (CurrentCallPoints > 0) ? gm.logicMgr.GetDDockDigimon(ddockIndex) : Constants.DEFAULT_DIGIMON;
            int callPointsBefore = CurrentCallPoints;
            isDDockUsed[ddockIndex] = true;

            currentScreen = BattleScreen.BattleCall_Menu;
            battleCallMenuIndex = 0;

            friendlyDigimon = gm.DatabaseMgr.GetDigimon(digimon)?? gm.DatabaseMgr.GetDigimon(Constants.DEFAULT_DIGIMON);
            CurrentCallPoints -= friendlyDigimon.GetCallCost(playerLevel);
            int friendlyDigimonLevel = gm.logicMgr.GetDigimonExtraLevel(digimon);
            friendlyStats = friendlyDigimon.GetFriendlyStats(friendlyDigimonLevel);

            awardSpiritPower = true;

            gm.UpdateLeaverBuster(defeatExp, friendlyDigimon.name);

            gm.EnqueueAnimation(gm.screenMgr.ASpendCallPoints(callPointsBefore, CurrentCallPoints));
            gm.EnqueueAnimation(gm.screenMgr.ASummonDigimon(digimon));
        }

        private void DeportCurrentDigimon() {
            string deportedDigimon = friendlyDigimon.name;

            friendlyDigimon = null;
            friendlyStats = null;
            awardSpiritPower = false;

            currentScreen = BattleScreen.MainScreen;

            gm.UpdateLeaverBuster(defeatExp, "");

            gm.EnqueueAnimation(gm.screenMgr.ADeportDigimon(deportedDigimon));
        }
        private void SubmitTurn(int friendlyAttack) {
            int SPbefore = gm.logicMgr.SpiritPower;
            if (awardSpiritPower) gm.logicMgr.SpiritPower += 3;

            int enemyAttack = ChooseEnemyAttack();
            int winner = ExecuteTurn(ref friendlyAttack, enemyAttack, out bool disobeyed, out int loserHPbefore);
            int loserHPnow = (winner == 0) ? enemyStats.HP : friendlyStats.HP;

            int friendlyEnergy = friendlyStats.GetEnergyRank();
            int enemyEnergy = enemyStats.GetEnergyRank();

            //Display spirits being lost if needed.

            gm.EnqueueAnimation(
                gm.screenMgr.ADisplayTurn(
                    friendlyDigimon.name, friendlyAttack, friendlyEnergy,
                    enemyDigimon.name, enemyAttack, enemyEnergy,
                    winner, disobeyed, loserHPbefore, loserHPnow)
                );
            if(awardSpiritPower) {
                gm.EnqueueAnimation(gm.screenMgr.AAWardSpiritPower(SPbefore));
            }

            //The player has won or lost the game.
            if (loserHPnow == 0) {
                VisualDebug.WriteLine($"A Digimon has reached 0 HP, and the winner of this round and thus the game is (0 or 1): {winner}.");
                if (winner == 0) {
                    WinBattle();
                }
                else {
                    LoseBattle();
                }
            }

        }
        private void WinBattle() {
            gm.DisableLeaverBuster();

            if (gm.logicMgr.AddPlayerExperience(victoryExp)) {
                gm.EnqueueAnimation(gm.screenMgr.ALevelUp(gm.logicMgr.GetPlayerLevel() - 1));
            }

            int distanceBefore = gm.DistanceMgr.CurrentDistance;
            gm.DistanceMgr.ReduceDistance(300, out _);
            int distanceAfter = gm.DistanceMgr.CurrentDistance;
            gm.EnqueueAnimation(gm.screenMgr.AChangeDistance(distanceBefore, distanceAfter));

            bool rewardEnemy = (Random.Range(0f, 1f) < enemyDigimon.GetRewardChance());
            if (isBossBattle) rewardEnemy = true;

            if (rewardEnemy) {
                if (gm.logicMgr.RewardDigimon(enemyDigimon.name, out int levelBefore, out int levelAfter)) {
                    gm.EnqueueAnimation(gm.screenMgr.ALevelUpDigimon(enemyDigimon.name, levelBefore, levelAfter));
                }
                else {
                    gm.EnqueueAnimation(gm.screenMgr.AUnlockDigimon(enemyDigimon.name));
                }
            }

            TriggerVictoryAgainstBoss();
        }

        private void LoseBattle() {
            gm.DisableLeaverBuster();

            if (gm.logicMgr.AddPlayerExperience(-defeatExp)) {
                gm.EnqueueAnimation(gm.screenMgr.ALevelDown(gm.logicMgr.GetPlayerLevel() - 1));
            }

            int distanceBefore = gm.DistanceMgr.CurrentDistance;
            int amountToIncrease = isBossBattle ? 500 : 300;
            gm.DistanceMgr.ReduceDistance(amountToIncrease, out _);
            int distanceAfter = gm.DistanceMgr.CurrentDistance;
            gm.EnqueueAnimation(gm.screenMgr.AChangeDistance(distanceBefore, distanceAfter));

            if (Random.Range(0f, 1f) < friendlyDigimon.GetPunishmentChance()) {
                if (gm.logicMgr.PunishDigimon(enemyDigimon.name, out int levelBefore, out int levelAfter)) {
                    gm.EnqueueAnimation(gm.screenMgr.ALevelDownDigimon(enemyDigimon.name, levelBefore, levelAfter));
                }
                else {
                    gm.EnqueueAnimation(gm.screenMgr.AEraseDigimon(enemyDigimon.name));
                }
            }
        }

        private void EscapeBattle() {
            gm.DisableLeaverBuster();

            if (gm.logicMgr.AddPlayerExperience(-defeatExp)) {
                gm.EnqueueAnimation(gm.screenMgr.ALevelDown(gm.logicMgr.GetPlayerLevel() - 1));
            }

            int distanceBefore = gm.DistanceMgr.CurrentDistance;
            gm.DistanceMgr.ReduceDistance(2000, out _);
            int distanceAfter = gm.DistanceMgr.CurrentDistance;
            gm.EnqueueAnimation(gm.screenMgr.AChangeDistance(distanceBefore, distanceAfter));
        }

        private List<IEnumerator> TriggerVictoryAgainstBoss() {
            return null;
        }

        /// <summary>
        /// Executes the turn and returns the winner. It also outputs the Attack chosen by the enemy
        /// and the life the loser had before being damaged.
        /// This method receives friendlyAttack by reference and will modify it if the Digimon decides to
        /// disobey.
        /// </summary>
        /// <param name="friendlyAttack">The Attack chosen by the player.</param>
        private int ExecuteTurn(ref int friendlyAttack, int enemyAttack, out bool disobeyed, out int loserHPbefore) {
            disobeyed = false;
            if (Random.Range(0f, 1f) > friendlyDigimon.GetIdleChance(playerLevel)) {
                friendlyAttack = 3;
                disobeyed = true;
                VisualDebug.WriteLine("The friendly digimon disobeyed and didn't attack.");
            }
            else if (Random.Range(0f, 1f) > friendlyDigimon.GetObeyChance(playerLevel)) {
                friendlyAttack = Random.Range(0, 3);
                disobeyed = true;
                VisualDebug.WriteLine("The friendly digimon disobeyed and used a random attack.");
            }

            int winner = ChooseWinner(friendlyAttack, enemyAttack, out int damageDealt);

            loserHPbefore = (winner == 0) ? enemyStats.HP : friendlyStats.HP;
            DamageDigimon((winner == 0) ? 1 : 0, damageDealt);

            return winner;
        }

        private int ChooseEnemyAttack() {
            int total = enemyStats.EN + enemyStats.CR + enemyStats.AB;
            int rngNumber = enemyAttackRNG.Next(total);

            if (rngNumber < enemyStats.EN) return 0;
            else if (rngNumber < enemyStats.EN + enemyStats.CR) return 1;
            else return 2;
        }

        private int ChooseWinner(int friendlyAttack, int enemyAttack, out int damageDealt) {
            int friendlyDamage = friendlyStats.GetAttackDamage(friendlyAttack);
            int enemyDamage = enemyStats.GetAttackDamage(enemyAttack);
            VisualDebug.WriteLine($"friendly damage: {friendlyDamage}, enemy damage: {enemyDamage}");
            if(friendlyAttack == 3) {
                damageDealt = enemyDamage;
                return 1;
            }
            else if(friendlyAttack == enemyAttack) {
                int difference = friendlyDamage - enemyDamage;
                damageDealt = Mathf.Abs(difference);

                //If both Digimons used Energy and their Energies have different rank (have different sprite), the higher rank energy always wins.
                if (friendlyAttack == 0 && friendlyStats.GetEnergyRank() != enemyStats.GetEnergyRank()) {
                    return (friendlyStats.GetEnergyRank() > enemyStats.GetEnergyRank()) ? 0 : 1;
                }
                //Else, if both Digimon
                else {
                    if (difference < -5) return 1; //The enemy dealt 5+ more damage than the player.
                    if (difference > 5) return 0; //The player dealt 5+ more damage than the enemy.
                    else return 2;
                }
            }
            else {
                if(friendlyAttack == 0) {
                    if (enemyAttack == 2) {
                        damageDealt = friendlyDamage;
                        return 0;
                    }
                    else if (enemyAttack == 1) {
                        damageDealt = enemyDamage;
                        return 1;
                    }
                }
                else if (friendlyAttack == 1) {
                    if (enemyAttack == 0) {
                        damageDealt = friendlyDamage;
                        return 0;
                    }
                    else if (enemyAttack == 2) {
                        damageDealt = enemyDamage;
                        return 1;
                    }
                }
                else if (friendlyAttack == 2) {
                    if (enemyAttack == 1) {
                        damageDealt = friendlyDamage;
                        return 0;
                    }
                    else if (enemyAttack == 0) {
                        damageDealt = enemyDamage;
                        return 1;
                    }
                }
            }

            VisualDebug.WriteLine("There was an unknown error choosing the winner of this round.");
            damageDealt = -1;
            return 2;
        }

        private void DamageDigimon(int digimon, int damage) {
            //Enemy bosses receive less damage from attacks.
            if(isBossBattle && digimon == 1) {
                damage -= Mathf.FloorToInt(20f + (0.3f * playerLevel));
                if (damage < 0) damage = 0;
            }

            if(digimon == 0) {
                friendlyStats.HP -= (friendlyStats.HP - damage > 0) ? damage : friendlyStats.HP;
            }
            else if (digimon == 1) {
                enemyStats.HP -= (enemyStats.HP - damage > 0) ? damage : enemyStats.HP;
            }
        }
    }
}